apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-server-role
  namespace: ns-two
rules:
- apiGroups:
  - "" # "" indicates the core API group
  - "apps"
  resources:
  - services
  - configmaps
  - pods
  - secrets
  - endpoints
  - deployments
  verbs:
  - list